### ISSUE TITLE
Archive Recommended 

### ISSUE THREAD

**Issue by Minion3665** [GenElectrovise/VIRPTEQ-Calc#2]
⚠️ This repository is depreciated and replaced but not archived ⚠️ 
I recommend archiving code you aren't working on anymore

**Comment by atom-dispencer** [comment]
Thank you Minion3665. This repository will be archived in the near future. It does, however, currently contain a useful backup of the old code which is why I have refrained from its deletion.
Thanks, GenElectrovise
